Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,14 +2,12 @@ name: Release
 
 on:
   workflow_dispatch:
-  schedule:
-    - cron: '0 17 * * *'
 
 permissions: {}
 
 jobs:
   create-metadata:
-    if: github.repository == 'awslabs/mcp'
+    if: github.repository == 'scottschreckengaust/mcp'
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -57,13 +55,13 @@ jobs:
           echo "npm_packages=$NPM" >> $GITHUB_OUTPUT
 
   update-packages:
-    if: github.repository == 'awslabs/mcp' && (needs.create-metadata.outputs.npm_packages != '[]' || needs.create-metadata.outputs.pypi_packages != '[]')
+    if: github.repository == 'scottschreckengaust/mcp' && (needs.create-metadata.outputs.npm_packages != '[]' || needs.create-metadata.outputs.pypi_packages != '[]')
     needs: [create-metadata]
     runs-on: ubuntu-latest
     permissions:
       contents: write
       pull-requests: write
-    environment: release
+    # environment: release
     outputs:
       changes_made: ${{ steps.commit.outputs.changes_made }}
     steps:
@@ -86,8 +84,8 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
         run: |
-          git config --global user.name "awslabs-mcp"
-          git config --global user.email "203918161+awslabs-mcp@users.noreply.github.com"
+          git config --global user.name "scottschreckengaust"
+          git config --global user.email "scottschreckengaust@users.noreply.github.com"
 
       - name: Commit changes
         id: commit
@@ -126,15 +124,15 @@ jobs:
           path: RELEASE_NOTES.md
 
   publish-pypi:
-    if: github.repository == 'awslabs/mcp' && needs.create-metadata.outputs.pypi_packages != '[]' && needs.create-metadata.outputs.pypi_packages != ''
+    if: github.repository == 'scottschreckengaust/mcp' && needs.create-metadata.outputs.pypi_packages != '[]' && needs.create-metadata.outputs.pypi_packages != ''
     needs: [update-packages, create-metadata]
     strategy:
       fail-fast: false
       max-parallel: 10
       matrix:
-        package: ${{ fromJson(needs.create-metadata.outputs.pypi_packages) }}
+        package: ["aws-api-mcp-server"] # ${{ fromJson(needs.create-metadata.outputs.pypi_packages) }}
     name: Build ${{ matrix.package }}
-    environment: release
+    # environment: release
     permissions:
       contents: read
       id-token: write # Required for trusted publishing
@@ -142,7 +140,7 @@ jobs:
     steps:
       - name: Clear Up Space (Agressively) for Multi-Architecture Builds that Run Out of Space
         if: contains(toJson('["aws-api-mcp-server"]'), matrix.package)
-        uses: awslabs/mcp/.github/actions/clear-space-ubuntu-latest-agressively@25167c70e07d52455d651af931970d0ffdac75c5
+        uses: .github/actions/clear-space-ubuntu-latest-agressively
 
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
@@ -154,6 +152,11 @@ jobs:
       - name: Install uv
         uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6.3.1
 
+      - name: DEBUGGER
+        run: |
+          ls -al .
+          ls -al src/${{ matrix.package }}
+
       - name: Set up Python
         uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
         with:
@@ -163,122 +166,122 @@ jobs:
         working-directory: src/${{ matrix.package }}
         run: uv sync --frozen --all-extras --dev
 
-      - name: Run pyright
-        working-directory: src/${{ matrix.package }}
-        run: uv run --frozen pyright
+      # - name: Run pyright
+      #   working-directory: src/${{ matrix.package }}
+      #   run: uv run --frozen pyright
 
-      - name: Generate Embeddings
-        if: matrix.package == 'aws-api-mcp-server'
-        working-directory: src/${{ matrix.package }}
-        run: uv run --frozen generate-embeddings
+      # - name: Generate Embeddings
+      #   if: matrix.package == 'aws-api-mcp-server'
+      #   working-directory: src/${{ matrix.package }}
+      #   run: uv run --frozen generate-embeddings
 
       - name: Build package
         working-directory: src/${{ matrix.package }}
         run: uv build
 
-      - name: Publish package to PyPI
-        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
-        with:
-          packages-dir: src/${{ matrix.package }}/dist
+      # - name: Publish package to PyPI
+      #   uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
+      #   with:
+      #     packages-dir: src/${{ matrix.package }}/dist
 
-      - name: Get Version from ${{ matrix.package }} Package
-        id: get-package-version
-        working-directory: src/${{ matrix.package }}
-        run: |
-          echo "version=$(uv tree 2> /dev/null | grep awslabs | sed -e 's/^.*[[:space:]]v\(.*\)/\1/g')" >> $GITHUB_OUTPUT
+      # - name: Get Version from ${{ matrix.package }} Package
+      #   id: get-package-version
+      #   working-directory: src/${{ matrix.package }}
+      #   run: |
+      #     echo "version=$(uv tree 2> /dev/null | grep awslabs | sed -e 's/^.*[[:space:]]v\(.*\)/\1/g')" >> $GITHUB_OUTPUT
 
-      - name: Build and Publish ${{ matrix.package }} Container
-        id: build-and-publish
-        uses: awslabs/mcp/.github/actions/build-and-push-container-image@9ae15a5007b0d2d13dd58a6660484c6962157566
-        if: hashFiles(format('./src/{0}/Dockerfile', matrix.package))
-        with:
-          image: ${{ matrix.package }}
-          version: ${{ steps.get-package-version.outputs.version || github.sha }}
-          public-erc-role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
-          public-erc-registry-alias: 'f3y8w4n0' # 'w3i4n7u1'
-          public-erc-aws-region: ${{ env.AWS_REGION || 'us-east-1' }}
+      # - name: Build and Publish ${{ matrix.package }} Container
+      #   id: build-and-publish
+      #   uses: ./.github/actions/build-and-push-container-image
+      #   if: hashFiles(format('./src/{0}/Dockerfile', matrix.package))
+      #   with:
+      #     image: ${{ matrix.package }}
+      #     version: ${{ steps.get-package-version.outputs.version || github.sha }}
+      #     public-erc-role-to-assume: ${{ secrets.AWS_ROLE_ARN_TO_ASSUME }}
+      #     public-erc-registry-alias: 'f3y8w4n0' # 'w3i4n7u1'
+      #     public-erc-aws-region: ${{ env.AWS_REGION || 'us-east-1' }}
 
-      - name: Display Image Version ${{ matrix.package }}
-        id: display-image-version
-        if: success() && steps.build-and-publish.outcome == 'success'
-        run: |
-          echo "version: ${VERSION}"
-        env:
-          VERSION: ${{ steps.build-and-publish.outputs.version }}
+      # - name: Display Image Version ${{ matrix.package }}
+      #   id: display-image-version
+      #   if: success() && steps.build-and-publish.outcome == 'success'
+      #   run: |
+      #     echo "version: ${VERSION}"
+      #   env:
+      #     VERSION: ${{ steps.build-and-publish.outputs.version }}
 
-  publish-npm:
-    if: github.repository == 'awslabs/mcp' && needs.create-metadata.outputs.npm_packages != '[]' && needs.create-metadata.outputs.npm_packages != ''
-    needs: [update-packages, create-metadata]
-    strategy:
-      fail-fast: false
-      matrix:
-        package: ${{ fromJson(needs.create-metadata.outputs.npm_packages) }}
-    name: Build ${{ matrix.package }}
-    environment: release
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-        with:
-          ref: ${{ needs.create-metadata.outputs.version }}
+  # publish-npm:
+  #   if: github.repository == 'awslabs/mcp' && needs.create-metadata.outputs.npm_packages != '[]' && needs.create-metadata.outputs.npm_packages != ''
+  #   needs: [update-packages, create-metadata]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       package: ${{ fromJson(needs.create-metadata.outputs.npm_packages) }}
+  #   name: Build ${{ matrix.package }}
+  #   environment: release
+  #   runs-on: ubuntu-latest
+  #   permissions:
+  #     contents: read
+  #   steps:
+  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  #       with:
+  #         ref: ${{ needs.create-metadata.outputs.version }}
 
-      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
-        with:
-          node-version-file: "src/${{ matrix.package }}/.node-version"
-          cache: npm
-          registry-url: 'https://registry.npmjs.org'
+  #     - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
+  #       with:
+  #         node-version-file: "src/${{ matrix.package }}/.node-version"
+  #         cache: npm
+  #         registry-url: 'https://registry.npmjs.org'
 
-      - name: Install dependencies
-        working-directory: src/${{ matrix.package }}
-        run: npm ci
+  #     - name: Install dependencies
+  #       working-directory: src/${{ matrix.package }}
+  #       run: npm ci
 
-      - name: Check if version exists on npm
-        working-directory: src/${{ matrix.package }}
-        run: |
-          VERSION=$(jq -r .version package.json)
-          if npm view --json | jq -e --arg version "$VERSION" '[.[]][0].versions | contains([$version])'; then
-            echo "Version $VERSION already exists on npm"
-            exit 1
-          fi
-          echo "Version $VERSION is new, proceeding with publish"
+  #     - name: Check if version exists on npm
+  #       working-directory: src/${{ matrix.package }}
+  #       run: |
+  #         VERSION=$(jq -r .version package.json)
+  #         if npm view --json | jq -e --arg version "$VERSION" '[.[]][0].versions | contains([$version])'; then
+  #           echo "Version $VERSION already exists on npm"
+  #           exit 1
+  #         fi
+  #         echo "Version $VERSION is new, proceeding with publish"
 
-      - name: Build package
-        working-directory: src/${{ matrix.package }}
-        run: npm run build
+  #     - name: Build package
+  #       working-directory: src/${{ matrix.package }}
+  #       run: npm run build
 
-      - name: Publish package
-        working-directory: src/${{ matrix.package }}
-        run: |
-          npm publish --access public
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+  #     - name: Publish package
+  #       working-directory: src/${{ matrix.package }}
+  #       run: |
+  #         npm publish --access public
+  #       env:
+  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
-  create-release:
-    if: github.repository == 'awslabs/mcp' && needs.update-packages.outputs.changes_made == 'true' && !failure() && !cancelled() && ( needs.publish-npm.result == 'success' || needs.publish-pypi.result == 'success')
-    needs: [update-packages, create-metadata, publish-pypi, publish-npm]
-    runs-on: ubuntu-latest
-    # environment: release
-    permissions:
-      contents: write
-    steps:
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  # create-release:
+  #   if: github.repository == 'awslabs/mcp' && needs.update-packages.outputs.changes_made == 'true' && !failure() && !cancelled() && ( needs.publish-npm.result == 'success' || needs.publish-pypi.result == 'success')
+  #   needs: [update-packages, create-metadata, publish-pypi, publish-npm]
+  #   runs-on: ubuntu-latest
+  #   # environment: release
+  #   permissions:
+  #     contents: write
+  #   steps:
+  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: Download release notes
-        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
-        with:
-          name: release-notes
+  #     - name: Download release notes
+  #       uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
+  #       with:
+  #         name: release-notes
 
-      - name: Create release
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
-        run: |
-          VERSION="${{ needs.create-metadata.outputs.version }}"
-          gh release create "$VERSION" \
-            --generate-notes \
-            --draft \
-            --verify-tag
-          gh release view "$VERSION" --json body | jq -r '.body' > GENERATED_NOTES.md
-          cat RELEASE_NOTES.md GENERATED_NOTES.md | gh release edit "$VERSION" \
-            --draft=false \
-            --notes-file -
+  #     - name: Create release
+  #       env:
+  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN}}
+  #       run: |
+  #         VERSION="${{ needs.create-metadata.outputs.version }}"
+  #         gh release create "$VERSION" \
+  #           --generate-notes \
+  #           --draft \
+  #           --verify-tag
+  #         gh release view "$VERSION" --json body | jq -r '.body' > GENERATED_NOTES.md
+  #         cat RELEASE_NOTES.md GENERATED_NOTES.md | gh release edit "$VERSION" \
+  #           --draft=false \
+  #           --notes-file -
